# Generated by Django 5.2.9 on 2025-12-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='poblacion',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='poblacion',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='superficie',
        ),
    ]
